"""Add user course assignments table

Revision ID: 5e521b26e602
Revises: f75385842e21
Create Date: 2025-09-08 18:36:46.183115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e521b26e602'
down_revision: Union[str, None] = 'f75385842e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(50), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.String(50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_course_assignments')
    # ### end Alembic commands ###
