name: Code Quality

on:
  push:
    tags:
      - 'v*.*.*'  # Только для стабильных релизов (v1.0.0, v2.1.3, etc.)
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запуск вручную

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort mypy
    
    - name: Run Black (code formatting check)
      run: |
        black --check --diff app/ tests/
    
    - name: Run isort (import sorting check)
      run: |
        isort --check-only --diff app/ tests/
    
    - name: Run Flake8 (linting)
      run: |
        flake8 app/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run MyPy (type checking)
      run: |
        mypy app/ --ignore-missing-imports --no-strict-optional
    
    - name: Check for security issues
      run: |
        pip install bandit
        bandit -r app/ -f json -o bandit-report.json || true
        bandit -r app/ -ll
    
    - name: Quality Summary
      run: |
        echo "✅ Code quality checks completed"
        echo "📊 Repository: ${{ github.repository }}"
        echo "🌿 Branch: ${{ github.ref_name }}"
        echo "👤 Actor: ${{ github.actor }}"
